version: '3'

networks:
    mynetwork:
        name: mynetwork

services:
    mysql:
        image: mysql
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=fiap
        ports:
            - '3306:3306'
        volumes:
            - ./data:/data/db
        healthcheck:
            test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            timeout: 2s
            retries: 10
        networks:
            - mynetwork

    node_pedido:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: node_pedido
        networks:
            - mynetwork
        ports:
            - '3000:3000'
        depends_on:
            mysql:
                condition: service_healthy
